version: '3.7'
services:
  postgres:
    container_name: simple-project-postgres
    image: postgres:16.12-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      PGUSER=postgres
      POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password 
    secrets:
      - postgres-password
    healthcheck:
      test: pg_isready -U postgres -d test
      interval: 1s
      timeout: 2s
      retries: 20 
    networks:
      - backend
  api:
    image: gawciuherodotus/simple-project
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL_FILE=/run/secrets/database-url
    secrets:
      - database-url
    networks: 
     - backend
volumes:
  pgdata:
networks:
  frontend:
  backend:
secrets:
  database-url:
    external: true
  postgres-password:
    external: true
  