version: '3.7'
services:
  postgres:
    container_name: simple-project-postgres
    image: postgres:16.12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    healthcheck:
      test: pg_isready -U postgres -d test
      interval: 1s
      timeout: 2s
      retries: 20 
  api:
    image: gawciuherodotus/simple-project
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/test
volumes:
  pgdata: 
  